/**
 * Generated API types — regenerated by `npx convex dev`.
 */
import type { ApiFromModules } from "convex/server";
import type * as users from "../users";

/**
 * A type describing your app's public Convex API.
 */
declare const fullApi: ApiFromModules<{
  users: typeof users;
}>;

export declare const api: typeof fullApi;
export declare const internal: typeof fullApi;
