/**
 * Generated API types — regenerated by `npx convex dev`.
 */
import type { ApiFromModules } from "convex/server";
import type * as activityLog from "../activityLog";
import type * as candidateFiles from "../candidateFiles";
import type * as candidatePositions from "../candidatePositions";
import type * as candidates from "../candidates";
import type * as organizations from "../organizations";
import type * as positions from "../positions";
import type * as users from "../users";

/**
 * A type describing your app's public Convex API.
 */
declare const fullApi: ApiFromModules<{
  activityLog: typeof activityLog;
  candidateFiles: typeof candidateFiles;
  candidatePositions: typeof candidatePositions;
  candidates: typeof candidates;
  organizations: typeof organizations;
  positions: typeof positions;
  users: typeof users;
}>;

export declare const api: typeof fullApi;
export declare const internal: typeof fullApi;
