/**
 * Generated data model types — regenerated by `npx convex dev`.
 */
import type { DataModelFromSchemaDefinition, GenericId } from "convex/server";
import type schema from "../schema";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;

export type Id<TableName extends keyof DataModel> = GenericId<TableName>;
