/**
 * Generated data model types — regenerated by `npx convex dev`.
 */
import type { DataModelFromSchemaDefinition } from "convex/server";
import type schema from "../schema";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
