/* eslint-disable */
/**
 * Generated server utilities — regenerated by `npx convex dev`.
 */
const {
  queryGeneric,
  mutationGeneric,
  actionGeneric,
} = require("convex/server");

exports.query = queryGeneric;
exports.internalQuery = queryGeneric;
exports.mutation = mutationGeneric;
exports.internalMutation = mutationGeneric;
exports.action = actionGeneric;
exports.internalAction = actionGeneric;
